### ISSUE TITLE
Chrome Driver staying open

### ISSUE THREAD

**Issue by zisop16** [TempJannik/Wizard101-Trivia-Bot#1]
The trivia bot does not completely close its instances of chrome.exe, thus leaving a giant list of processes open in task manager and taking up empty memory. Please fix this :D

**Comment by TempJannik** [comment]
Hi,
can you please provide some additional information?
-Were you running in Headless mode?
-Were you running via Python or the compiled version?

**Comment by zisop16** [comment]
I was running using headless mode in python.

**Comment by TempJannik** [comment]
Unfortunately I was unable to reproduce this.
During execution with 2 Threads, Headless mode in Python these are the created processes: https://i.imgur.com/BHtNcIo.png
After it has finished and the Selenium.WebDriver.Quit function has been called, chromedriver.exe ends and so do the Chrome instances for me, see here: https://i.imgur.com/cgkNo1r.png
After pressing enter it also exits the Python instance, leaving just the command prompt.

If you can provide more details, a demonstration or some more info to help me reproduce this Ill look into it again.

**Comment by zisop16** [comment]
It appears that the bug only occurs when closing the .exe early
https://youtu.be/pi6YFU6-sNc

**Comment by TempJannik** [comment]
Yeah that makes more sense. I'm not sure if I can properly handle a process exit without going through a ton of workarounds. 
If you can find a good solution that doesn't rely on any external libraries to fix this feel free to make a pull request, I don't think I will be looking into this any further.
