### ISSUE TITLE
Switch case statements not implemented correctly

### ISSUE THREAD

**Issue by zisop16** [TempJannik/Wizard101-Trivia-Bot#5]
In your solve trivia question method, you have a switch case implemented using "switcher" objects. However, each time the trivia question goes to solve, it is creating new switcher objects, thus being significantly slower than just creating a giant list of IF statements. This can be fixed by making sure you only create one instance of these switcher objects in a global context.

**Comment by TempJannik** [comment]
Took a little test benchmarking 3 Methods,
Switches - 0.79s
If Statements - 0.59s
Switches with Global context - 0.192s

While Im not too worried about performance since KI ratelimits anyways I'll add this in the next release, thanks.

**Comment by TempJannik** [comment]
Fixed. Thanks for the submission. 
https://github.com/TempJannik/Wizard101-Trivia-Bot/commit/6e591778c759c3e0f9915962fbaaa915f4027f28
