### ISSUE TITLE
"Image.png" overwritten by other threads

### ISSUE THREAD

**Issue by zisop16** [TempJannik/Wizard101-Trivia-Bot#6]
Because the program only has one copy of image.png, different threads interfere and produce errors occasionally

**Comment by TempJannik** [comment]
I've never experienced this personally but it sounds like something that could definitely happen. Will also try to fix for the next update

**Comment by TempJannik** [comment]
Fixed. Thanks for the submission. 
https://github.com/TempJannik/Wizard101-Trivia-Bot/commit/6e591778c759c3e0f9915962fbaaa915f4027f28
